### ISSUE TITLE
Handle message edit as new message

### ISSUE THREAD

**Issue by kurnevsky** [dylex/slack-libpurple#5]
It's very inconvenient when you can't see message changes so you can miss some important information. Other protocols handle edits like new message.

**Comment by zoltan-dulac** [comment]
I have implemented this in PR https://github.com/dylex/slack-libpurple/pull/21

Note that the edited text doesn't appear like the official slack plugin, due to pidgin not being able to "rewrite history" (as far as I know).  The text appears like the screenshot below.  Please let me know if this is acceptable or not. 

![slack-pidgin-edit-text](https://user-images.githubusercontent.com/281398/34502570-0ba1a092-efe2-11e7-9c6c-67c5a516bf08.jpg)

**Comment by dylex** [comment]
This is done now, pretty much as above, thanks to @zoltan-dulac.
