### ISSUE TITLE
support Spectrum2

### ISSUE THREAD

**Issue by thundergreen** [dylex/slack-libpurple#51]
Hi. NIce PLugin. BUt I Try to register via Vacuum for slack but dunno how. Username and password are the for registering.

How would i archieve to register for libpurple spectrum2 ?

**Comment by dylex** [comment]
I'm not sure what vacuum or spectrum2 are, but assuming they use libpurple, you should be able to follow similar instructions as the readme: issue a personal slack api token and enter it in `api_token` -- you can't use password authentication.

**Comment by rhaas80** [comment]
Having used spectrum myself (though not yet with this slack->purple library) and assuming you are using something like Adium (OSX) or Pidgin (Linux, Windows) as your client then I usually end up having to do one of two things:

- if I am lucky then when registering a transport pigidn actually presents a field for the API token
- if I am unlucky (one usually is) then I end up having to first set things up in my pidgin client locally then look at $HOME/.purple/accounts.xml and copy the interesting lines out of the slack account settings into the [purple] section of the corresponding transport cfg file of spectrum2. This of course assumes that you are running your own spectrum2 or at least that the cfg files (which contain effectively a password to your slack account) are not accessible by anyone else.

Note that I have not tested this myself yet (due to lack of time mostly given that the slack xmpp gateway will go away soon so I will have to give this a try myself soon).

**Comment by dylex** [comment]
Not sure if this helps, but as per #47 I've changed it to fall back to password as the token, if it's easier to enter password but not api_token (note: it's still the api token, not your slack password, it just goes in the password field).

**Comment by dylex** [comment]
From other issues, it sounds to me like at least some people are at least partly successfully using spectrum2, so I'm closing this general issue. If there are still basic issues feel free to open them.
