### ISSUE TITLE
Integration attachment not displayed

### ISSUE THREAD

**Issue by nicorikken** [dylex/slack-libpurple#7]
When I receive a message from an integration, like a GitLab [webhook](https://api.slack.com/custom-integrations/incoming-webhooks), I only see the `text` from the root, but not the `text` in the `attachment`s.

In the case of GitLab webhooks the most relevant information is in the attachments:

### Commented
**Text**: `<user>` commented on merge request `<MR number>` in `<project>`: `<MR name>`
**Attachment text**: `<actual comment>`

### Build result
**Text**: (none)
**Attachment text**: `<project>`: Pipeline `<pipeline number>` of branch `<branch name>` by `<user>` passed in `<duration>`

**Comment by nicorikken** [comment]
If I understand the code correctly, only the `text` key is currently used. https://github.com/dylex/slack-libpurple/blob/master/slack-message.c#L147 This should then be extended to cover the attchments. A rendering convention should be defined.

**Comment by nicorikken** [comment]
In trying to figure out how to deal with attachments, I get the sense that I should acquire a pointer to the attachments ([doc](https://api.slack.com/docs/message-attachments)) section in the `handle_message` function in `slack-message.c`, and pass that in to `slack_message_to_html` function where the attachment(s) are formatted. This could be a subroutine, as it can become quite complex.
I'm not familiar with libpurple, and my C skills are quite limited, so any ideas or help is welcome.

**Comment by dylex** [comment]
Your assessment is correct. I think the main challenge here is determining a generic way to convert all the various metadata stuff in a message, including reactions, edits, attachments, etc. to a single purple formated message. If you'd like to propose something (formatting and logic) that makes sense as a starting point, I'd be happy to implement it in `handle_message` and `slack_message_to_html`. It'd be great if it also covered #5 somehow. Ideally each message would only generate one purple message, but this isn't strictly necessary, as we can also use `purple_conversation_write` to display additional non-message text.

**Comment by zoltan-dulac** [comment]
I offered to help @dylex on this, so I am commenting here on a first pass of attachments.  Take a look at the screenshot below (the left is the slack webclient, the right is my copy of pidgin with the modified slack-libpurple plugin.

![screenshot-slack-plugin-attachments](https://user-images.githubusercontent.com/281398/34014813-78f471ee-e0ea-11e7-9aff-e504b7b6cdea.jpg)

I am not sure about the formatting.  Any ideas would be welcome. Note the Twitter attachment -- you'll see I tried integrating the colors the best I could.  It can't really do the vertical bars (at least the same way) as the original Slack because vertical bars can't span more than one line (since I'd have to insert a pipe at the beginning of each line for the attachments).  This is the reason why the colors appear on horizontal bars (using m-dashes).

@nicorikken Is right -- this was really complicated to do, and I'm not even sure I got all possible attachement scenarios.  I used [Slack's documentation on the attachment API as a source](https://api.slack.com/docs/message-attachments), but I noticed that it was not 100% complete (e.g. there were extra fields I have seen, like `author_subname`. which wasn't listed in that doc).


Any thoughts, comments, are welcome here.

**Comment by dylex** [comment]
This looks like a good start to me -- I'd be happy to review and merge it.  Here's a github integration json attachment for reference:
```json
{
   "event_ts" : "1514670269.000048",
   "text" : "",
   "team" : "TXXXXXXXX",
   "channel" : "GXXXXXXXX",
   "ts" : "1514670269.000048",
   "bot_id" : "BXXXXXXX",
   "type" : "message",
   "subtype" : "bot_message",
   "attachments" : [
      {
         "pretext" : "<https://github.com/user/repo/tree/master|[repo:master]> 1 new commit by Dylan Simon:",
         "text" : "`<https://github.com/user/repo/commit/xxxxxx|xxxxxx>` blah blah - Dylan Simon",
         "mrkdwn_in" : [
            "text",
            "pretext"
         ],
         "id" : 1,
         "color" : "4183C4",
         "fallback" : "<https://github.com/user/repo/tree/master|[repo:master]><https://github.com/user/repo/commit/xxxxxxx|1 new commit> by Dylan Simon"
      }
   ]
}
```

**Comment by zoltan-dulac** [comment]
I have posted a PR: https://github.com/dylex/slack-libpurple/pull/21

Note that I don't have github integration set up on my slack instance. @dylex Can you test this for me.  I think it should work (it works with other bot messages) but I would want to make sure it works for all (I don't implement "mrkdwn_in", so I am not sure if that is necessary or not).

**Comment by dylex** [comment]
This is done now and generally seems to work, thanks to @zoltan-dulac.  Feel free to open another issue for any other unhandled attachments or tweaks.
