### ISSUE TITLE
Outgoing OTR messages only appear as OTR

### ISSUE THREAD

**Issue by frh** [dylex/slack-libpurple#80]
When sending private messages encrypted with pidgin-otr, all incoming messages are displayed correctly, but outgoing messages appear just in their OTR-encrypted form. They display fine for the recipient.

Could this be from the duplicate outgoing message fix?

**Comment by dylex** [comment]
Yes, sounds like #79 would cause this, since slack insists on sending you copies of the messages you send. Since these messages arrive before the send receipt comes, we have no choice but to suppress the normal sent message display.

I'm not optimistic there's a fix for this and #79 given what slack's doing. Does slack actually support OTR somehow? If so, there may be some way to figure out the message is otr and do something else (though it's not clear what). Or is this only to other libpurple users?

**Comment by frh** [comment]
Slack does not have anything that supports or impedes OTR. OTR can be sent over any text protocol. In the Slack client it only appears as OTR nonsense, while to clients that support OTR (like Pidgin with pidgin-otr) it will be interpreted by the OTR plugin.

All OTR messages begin with "?OTR", so they can be easily identified.

**Comment by dylex** [comment]
In that case, it seems like the otr plugin itself would have to deal with this case. The messages essentially appear as remote-sent outgoing messages.

**Comment by frh** [comment]
When you send a message with pidgin-otr, the outgoing message that appears in the client is the plaintext, while what gets sent out is the ciphertext. Before #79 was an issue, this worked perfectly. Once duplicate messages started appearing, outgoing OTR would appear twice, once as the plaintext echoed by Pidgin, and once as the ciphertext returned by Slack. Unfortunately the fix removed Pidgin's plaintext echo.

Would this be impossible to fix or work around in slack-libpurple? pidgin-otr has unfortunately not seen any new commits for two years, so it seems to be unlikely to be fixed there. Keeping messages unreadable by Slack admins is a major advantage of slack-libpurple + pidgin-otr.

**Comment by dylex** [comment]
I could provide an option to display both messages as it was without the #79 fix. At the point slack sends a copy of the outgoing message, there is literally no way to know for sure that it's a message we're sending rather than one being sent from somewhere else (with the same text). We could delay displaying such messages until we get a response from all un-acknowledged sent messages, but this would defeat the purpose of slack's new behavior: they want you to display this message rather than the one you typed, because it has all the server-side formatting applied.

Theoretically, slack-libpurple could detect OTR messages and do something different. I'd accept a PR to that effect, if it only affected OTR messages with an option, but that seems slightly hacky.

**Comment by frh** [comment]
The solution of delaying the display (as an option, off by default) seems like the best one. Losing Slack's server-side formatting is a lot more livable than losing OTR or having all messages duplicated.

**Comment by dylex** [comment]
Okay, that seems reasonable, and I'd support such work, though won't have much to contribute myself. It's a fairly sizable endeavour since it requires keeping some extra state per channel object.  I'd suggest keeping two lists of messages: one of unacknowledged sends and one of delayed messages. If there are any unacknowledged sends, queue any incoming messages. On acknowledgement, walk through the queue and compare message timestamps. It's not entirely clear how to deal with multiple outstanding messages and when to clear out the other queued messages. Happy to talk through any thoughts and review a PR.

**Comment by frh** [comment]
Unfortunately I've never written any libpurple code, and my C knowledge is rudimentary at best. Perhaps I'll take a crack at this at some point. Thanks for the guidance for if I do try.

**Comment by ordex** [comment]
I am interested in this too as now my OTR'd PMs are "a bit more complex to read" hehe.
I haven't checked the code at all, but imho we should make an effort to think about something simpler. 

First of all: anybody knows why isn't the pridgin-otr plugin throwing an error?
The "outgoing" message that comes back from slack should be an "undecryptable OTR message" (I think), hence the OTR plugin should complain about it.

**Comment by theycallme-west** [comment]
OTR is my main reason for using slack-libpurple. Definitely more annoying now. I would appreciate any fix no matter how "hackish". Unfortunately I do not have the programming skills to try and fix it myself.

**Comment by dylex** [comment]
I've thought of another possible way to deal with this, but it may be too broad. If we have an option to simply not display any remote-sent messages that look like OTR, the original message should be unsuppressed. Is that acceptable? It would mean that any message sent from another client that starts with `?OTR` would simply disappear (with this option on).

**Comment by ordex** [comment]
it may make sense. The question is: what might we break by doing that? if somebody writes you with OTR enabled for whatever reason and your pidgin-otr plugin is not enabled/installed, you will not see anything. Might be acceptable (?)

**Comment by frh** [comment]
I think that sounds like a pretty good workaround. If you make it off by default, then people without pidgin-otr can simply not turn the option on.

**Comment by ordex** [comment]
checking out commit ed82bbe93642f145c6c8ab662550ca2783bbb50b seems to make everything stable again - not sure why/how/what/if

**Comment by ordex** [comment]
@dylex yeah I remember that issue, but apparently it works as expected after having gone back to  ed82bbe
Maybe slack has changed something else again?

**Comment by theycallme-west** [comment]
ed82bbe works for me too. I only get the initial ?OTR when I initiate OTR.

**Comment by frh** [comment]
Same result here, running ed82bbe provides perfect results for me apart from the initial ?OTR noise. No duplicate messages in any other channels or chats either.

**Comment by frh** [comment]
I'm still on the latest commit but with ee0f2bd49e526a38525eadd6fbdf27e9488719f0 reverted, and I don't see duplicate messages. Looks like Slack rolled back their change. I'm wondering if that commit can be reverted since it no longer serves a purpose and so those who rely on OTR don't have to make local modifications.

**Comment by dylex** [comment]
Sounds good to me. I'll revert and put a note on the original issue in case it reappears for anyone.
